# Generated by Django 5.2.7 on 2025-11-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_post_author_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_create_post', 'Can create a post'), ('can_edit_post', 'Can edit own post'), ('can_delete_post', 'Can delete own post')]},
        ),
    ]
